name: Buildfreedom2
main: me.Creepercoders.Buildfreedom2.Buildfreedom2
version: 1.2.2
description: A Minecraft plugin that that allows custom features and commands.
author: zd12
commands:
  buildfreedom2:
    description: Plugin information.
    usage: /<command>
  bsaconfig:
    description: Console command - Demote/promote a player.
    usage: /<command> <add|delete> <username>
