name: Buildfreedom2
main: me.Creepercoders.Buildfreedom2.Buildfreedom2
version: 1.0
description: The official Sequal plugin for buildfreedom
author: xbuildcarter8
website: http://creepercoders.tk
commands:
  buildfreedom2:
    description: Plugin information.
  bsaconfig:
    description: Console command - Demote/promote a player.
    usage: /<command> <add|delete> <username>
