name: Buildfreedom2
main: me.Creepercoders.Buildfreedom2.Buildfreedom2
version: 2.0
description: The official sequal to the official plugin for PVPCraft.
author: xXWilee999Xx and buildcarter8
website: http://creepercoders.tk
commands:
  buildfreedom2:
    description: Plugin information.
  bsaconfig:
    description: Console command - Demote/promote a player.
    usage: /<command> <add|delete> <username>
